services:
  vps-backup:
    build: .
    container_name: vps-backup
    ports:
      - "8080:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./data:/data
    restart: unless-stopped
